### ISSUE TITLE
iOS detailview

### ISSUE THREAD

**Issue by manumaticx** [manumaticx/photogrid#1]
- photoview not working correctly on iOS
- needs navigationbar
- not tested on iOS 6.0

**Comment by jmcerrejon** [comment]
Any progress with that?

**Comment by manumaticx** [comment]
I refactored the code earlier this year and I do think it *should* work on iOS, doesn't it? I'll have a look at this next week if it needs corrections.

**Comment by jmcerrejon** [comment]
It has an unusual behavior:

* On iOS, It does not show in the grid, remote images

* On Android, the grid works ok, but always show the same image on photoview(index=1).

**Comment by jmcerrejon** [comment]
Did you have a look to the issues? Maybe I can help you.

**Comment by manumaticx** [comment]
Hey, I'm just back from vacation and will check this out as soon as possible

**Comment by mcvendrell** [comment]
You have a PR with the fix, Manu.
