### ISSUE TITLE
I think it does not work with the new 4.1.0 SDK

### ISSUE THREAD

**Issue by jmcerrejon** [manumaticx/photogrid#4]
Both iOS and Android get the next issue: 

**Object # View has no method open on createWindow**

**Comment by manumaticx** [comment]
The readme is not up-to-date. You'd use it like this:

__view__
```xml
<Widget id="photogrid" src="de.manumaticx.photogrid" />
```

__controller__
```js
$.photogrid.init();
$.photogrid.setData(data);
```

**Comment by manumaticx** [comment]
I refactored the code. You can now put the photogrid into your layout (it was a standalone window before). I just forgot to update the readme.

**Comment by manumaticx** [comment]
please, let me know if it works for you

**Comment by jmcerrejon** [comment]
Yes Manu, It works on both platforms. Thank you :)

**Comment by manumaticx** [comment]
great :)
